import { ActivityManager } from "../activityForward";

/** @type { CustomActivity []} */
const activities = [
    {
        activity: {
            Name: "踮起双脚",
            Prerequisite: ["UseFeet"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemBoots"],
        },
        useImage: "Kick",
        labelSelf: {
            CN: "踮起双脚",
            EN: "Stand on Tiptoes",
            RU: "Встать на Цыпочки",
            UA: "Встати навшпиньках",
        },
        dialogSelf: {
            CN: "SourceCharacter踮起PronounPossessive的双脚.",
            EN: "SourceCharacter stands on tiptoes.",
            RU: "SourceCharacter встает на цыпочки.",
            UA: "SourceCharacter встає навшпиньках",
        },
    },
    {
        activity: {
            Name: "摇晃脚踝",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemBoots"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "摇晃脚踝",
            EN: "Wiggle Ankles",
            RU: "Покачиваться",
            UA: "Трусити щиколотками",
        },
        dialogSelf: {
            CN: "SourceCharacter摇晃PronounPossessive的脚踝.",
            EN: "SourceCharacter wiggles PronounPossessive ankles.",
            RU: "SourceCharacter покачивается стоя на ногах.",
            UA: "SourceCharacter трусить щиколотками.",
        },
    },
    {
        activity: {
            Name: "伸出脚",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemBoots"],
        },
        useImage: "Kick",
        labelSelf: {
            CN: "伸出脚",
            EN: "Extend Leg",
            RU: "Приподнять Ногу",
            UA: "Підставити ногу",
        },
        dialogSelf: {
            CN: "SourceCharacter伸出PronounPossessive的脚.",
            EN: "SourceCharacter extends PronounPossessive leg.",
            RU: "SourceCharacter приподнимает свою ногу.",
            UA: "SourceCharacter підставляє ногу.",
        },
    },
    {
        activity: {
            Name: "掰开双腿",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 500,
            MaxProgressSelf: 50,
            Target: ["ItemLegs"],
        },
        useImage: "Wiggle",
        label: {
            CN: "掰开双腿",
            EN: "Spread Legs",
            RU: "Раздвинуть Ноги",
            UA: "Розширити ноги",
        },
        dialog: {
            CN: "SourceCharacter掰开TargetCharacter的双腿.",
            EN: "SourceCharacter spreads DestinationCharacter legs.",
            RU: "SourceCharacter раздвигает ноги TargetCharacter.",
            UA: "SourceCharacter Розширює ноги TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "夹紧双腿",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            MaxProgressSelf: 500,
            Target: [],
            TargetSelf: ["ItemLegs"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "夹紧双腿",
            EN: "Squeeze thighs",
            RU: "Сжать Ляжки",
            UA: "Стиснути стегна",
        },
        dialogSelf: {
            CN: "SourceCharacter夹紧了自己的腿.",
            EN: "SourceCharacter clamps PronounPossessive own thighs.",
            RU: "SourceCharacter сжимает свои ляжки.",
            UA: "SourceCharacter стискає свої стегна",
        },
    },
    {
        activity: {
            Name: "脚托起下巴",
            Prerequisite: ["TargetKneeling"],
            MaxProgress: 50,
            Target: ["ItemMouth"],
        },
        useImage: "Wiggle",
        label: {
            CN: "脚托起下巴",
            EN: "Foot on Chin",
            RU: "Ногу на Подбородок",
            UA: "Ногу на підборідок",
        },
        dialog: {
            CN: "SourceCharacter用脚托起TargetCharacter的下巴.",
            EN: "SourceCharacter places foot on DestinationCharacter chin.",
            RU: "SourceCharacter ставит ногу на подбородок TargetCharacter",
            UA: "SourceCharacter підставляє свою ногу на підборідок TargetCharacter.",
        },
    },

    {
        activity: {
            Name: "捏脸",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemMouth"],
            TargetSelf: true,
        },
        useImage: "Pinch",
        label: {
            CN: "捏脸",
            EN: "Pinch Face",
            RU: "Ущипнуть за Лицо",
            UA: "Вщипнути обличчя",
        },
        dialog: {
            CN: "SourceCharacter捏了捏TargetCharacter的脸.",
            EN: "SourceCharacter pinches DestinationCharacter face.",
            RU: "SourceCharacter щипает TargetCharacter за лицо.",
            UA: "SourceCharacter вщипує обличчя TargetCharacter.",
        },
        labelSelf: {
            CN: "捏脸",
            EN: "Pinch Face",
            RU: "Ущипнуть за Лицо",
            UA: "Вщипнути обличчя",
        },
        dialogSelf: {
            CN: "SourceCharacter捏了捏自己的脸.",
            EN: "SourceCharacter pinches own face.",
            RU: "SourceCharacter щипает свое лицо.",
            UA: "SourceCharacter вщипує своє обличчя.",
        },
    },
    {
        activity: {
            Name: "戳手臂",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemArms"],
            TargetSelf: true,
        },
        useImage: "Caress",
        label: {
            CN: "戳手臂",
            EN: "Poke Arm",
            RU: "Тыкнуть в Руку",
            UA: "Тицяти руку",
        },
        dialog: {
            CN: "SourceCharacter戳了戳TargetCharacter的手臂.",
            EN: "SourceCharacter pokes DestinationCharacter arm.",
            RU: "SourceCharacter тыкает TargetCharacter в руку.",
            UA: "SourceCharacter тицяє руку TargetCharacter.",
        },
        labelSelf: {
            CN: "戳手臂",
            EN: "Poke Arm",
            RU: "Тыкнуть в Руку",
            UA: "Тицяти руку",
        },
        dialogSelf: {
            CN: "SourceCharacter戳了戳自己的手臂.",
            EN: "SourceCharacter pokes own arm.",
            RU: "SourceCharacter тычет в собственную руку.",
            UA: "SourceCharacter тицяє свою руку.",
        },
    },
    {
        activity: {
            Name: "揉脸",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemMouth"],
            TargetSelf: true,
        },
        useImage: "Wiggle",
        label: {
            CN: "揉脸",
            EN: "Rub Face",
            RU: "Потереть Лицо",
            UA: "Потерти обличчя",
        },
        dialog: {
            CN: "SourceCharacter揉了揉TargetCharacter的脸.",
            EN: "SourceCharacter rubs DestinationCharacter face.",
            RU: "SourceCharacter трет лицо TargetCharacter.",
            UA: "SourceCharacter тре обличчя TargetCharacter.",
        },
        labelSelf: {
            CN: "揉脸",
            EN: "Rub Face",
            RU: "Потереть Лицо",
            UA: "Потерти обличчя",
        },
        dialogSelf: {
            CN: "SourceCharacter揉了揉自己的脸.",
            EN: "SourceCharacter rubs own face.",
            RU: "SourceCharacter трет свое лицо.",
            UA: "SourceCharacter тре своє обличчя.",
        },
    },
    {
        activity: {
            Name: "摇晃手臂",
            Prerequisite: ["UseHands"],
            MaxProgress: 50,
            Target: ["ItemArms"],
            TargetSelf: true,
        },
        useImage: "Wiggle",
        label: {
            CN: "摇晃手臂",
            EN: "Shake Arms",
            RU: "Трясти за Плечи",
            UA: "Трусити руки",
        },
        dialog: {
            CN: "SourceCharacter摇晃TargetCharacter的手臂.",
            EN: "SourceCharacter shakes DestinationCharacter arms.",
            RU: "SourceCharacter трясет TargetCharacter за плечи .",
            UA: "SourceCharacter трусить руки TargetCharacter.",
        },
        labelSelf: {
            CN: "摇晃手臂",
            EN: "Shake Arms",
            RU: "Пожать Плечами",
            UA: "Трусити руками",
        },
        dialogSelf: {
            CN: "SourceCharacter摇晃自己的手臂.",
            EN: "SourceCharacter shakes own arms.",
            RU: "SourceCharacter пожимает плечами.",
            UA: "SourceCharacter трусить свої руки.",
        },
    },
    {
        activity: {
            Name: "轻推",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemTorso"],
        },
        useImage: "Slap",
        label: {
            CN: "轻推",
            EN: "Light Push",
            RU: "Легонько Толкнуть",
            UA: "Ніжно штовхнути",
        },
        dialog: {
            CN: "SourceCharacter用手轻推TargetCharacter的身体.",
            EN: "SourceCharacter lightly pushes DestinationCharacter body.",
            RU: "SourceCharacter легонько толкает TargetCharacter",
            UA: "SourceCharacter легенько штовхає TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "托起脚",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemBoots"],
        },
        useImage: "Caress",
        label: {
            CN: "托起脚",
            EN: "Lift Foot",
            RU: "Приподнять Ступню",
            UA: "Підняти ногу",
        },
        dialog: {
            CN: "SourceCharacter托起TargetCharacter的脚.",
            EN: "SourceCharacter lifts DestinationCharacter foot.",
            RU: "SourceCharacter приподнимает ступню TargetCharacter",
            UA: "SourceCharacter ніжно піднімає ногу TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "扭动手腕",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHands"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "扭动手腕",
            EN: "Twist Wrists",
            RU: "Вращать Кистями",
            UA: "Скрутити зап'ястя",
        },
        dialogSelf: {
            CN: "SourceCharacter扭动PronounPossessive的手腕.",
            EN: "SourceCharacter twists PronounPossessive wrists.",
            RU: "SourceCharacter вращает кистями.",
            UA: "SourceCharacter скручує собі зап'ястя.",
        },
    },
    {
        activity: {
            Name: "挠头",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHead"],
        },
        useImage: "Pull",
        labelSelf: {
            CN: "挠头",
            EN: "Scratch Head",
            RU: "Почесать Голову",
            UA: "Почухати голову.",
        },
        dialogSelf: {
            CN: "SourceCharacter挠了挠PronounPossessive的头.",
            EN: "SourceCharacter scratches PronounPossessive own head",
            RU: "SourceCharacter чешет голову.",
            UA: "SourceCharacter чухає свою голову.",
        },
    },
    {
        activity: {
            Name: "盖住耳朵",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemEars"],
            TargetSelf: true,
        },
        useImage: "HandGag",
        label: {
            CN: "盖住耳朵",
            EN: "Cover Ears",
            RU: "Закрыть Уши",
            UA: "Закрити вуха",
        },
        dialog: {
            CN: "SourceCharacter用手盖住了TargetCharacter的耳朵.",
            EN: "SourceCharacter covers DestinationCharacter ears with hands.",
            RU: "SourceCharacter прикрывает уши TargetCharacter руками.",
            UA: "SourceCharacter закриває вуха TargetCharacter.",
        },
        labelSelf: {
            CN: "盖住耳朵",
            EN: "Cover Ears",
            RU: "Закрыть Уши",
            UA: "Закрити вуха",
        },
        dialogSelf: {
            CN: "SourceCharacter用手盖住了自己的耳朵.",
            EN: "SourceCharacter covers own ears with hands.",
            RU: "SourceCharacter прикрывает свои уши руками.",
            UA: "SourceCharacter закриває свої вуха",
        },
    },
    {
        activity: {
            Name: "遮住眼睛",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemHead"],
            TargetSelf: true,
        },
        useImage: "HandGag",
        label: {
            CN: "遮住眼睛",
            EN: "Cover Eyes",
            RU: "Прикрыть Глазки",
            UA: "Прикрити очі",
        },
        dialog: {
            CN: "SourceCharacter用手遮住了TargetCharacter的眼睛.",
            EN: "SourceCharacter covers DestinationCharacter eyes with hands.",
            RU: "SourceCharacter прикрывает глазки TargetCharacter своими руками.",
            UA: "SourceCharacter закриває очі TargetCharacter.",
        },
        labelSelf: {
            CN: "遮住眼睛",
            EN: "Cover Eyes",
            RU: "Прикрыть Глазки",
            UA: "Прикрити очі",
        },
        dialogSelf: {
            CN: "SourceCharacter用手遮住了自己的眼睛.",
            EN: "SourceCharacter covers PronounPossessive own eyes with hands.",
            RU: "SourceCharacter прикрывает свои глазки руками.",
            UA: "SourceCharacter прикриває свої очі руками.",
        },
    },
    {
        activity: {
            Name: "捂住头",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemHead"],
            TargetSelf: true,
        },
        useImage: "HandGag",
        label: {
            CN: "捂住头",
            EN: "Cover Head",
            RU: "Прикрыть Голову",
            UA: "Прикрити голову",
        },
        dialog: {
            CN: "SourceCharacter捂住TargetCharacter的头.",
            EN: "SourceCharacter covers DestinationCharacter head with hands.",
            RU: "SourceCharacter закрывает голову TargetCharacter руками.",
            UA: "SourceCharacter прикриває голову TargetCharacter своїми руками.",
        },
        labelSelf: {
            CN: "捂住头",
            EN: "Cover Head",
            RU: "Прикрыть Голову",
            UA: "Прикрити голову",
        },
        dialogSelf: {
            CN: "SourceCharacter捂住自己的头.",
            EN: "SourceCharacter covers own head with hands.",
            RU: "SourceCharacter закрывает свою голову руками.",
            UA: "SourceCharacter прикриває свою голову руками.",
        },
    },
    {
        activity: {
            Name: "捂住下体",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemVulva"],
            TargetSelf: true,
        },
        useImage: "HandGag",
        label: {
            CN: "捂住下体",
            EN: "Cover Groin",
            RU: "Прикрыть Промежность",
            UA: "Прикрити пах",
        },
        dialog: {
            CN: "SourceCharacter捂住TargetCharacter的下体.",
            EN: "SourceCharacter covers DestinationCharacter groin with hands.",
            RU: "SourceCharacter прикрывает промежность TargetCharacter своими руками.",
            UA: "SourceCharacter прикриває пах TargetCharacter.",
        },
        labelSelf: {
            CN: "捂住下体",
            EN: "Cover Groin",
            RU: "Прикрыть Промежность",
            UA: "Прикрити пах",
        },
        dialogSelf: {
            CN: "SourceCharacter捂住自己的下体.",
            EN: "SourceCharacter covers own groin with hands.",
            RU: "SourceCharacter прикрывает свою промежность руками.",
            UA: "SourceCharacter прикриває свій пах.",
        },
    },
    {
        activity: {
            Name: "掀开裙子",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemButt"],
            TargetSelf: true,
        },
        useImage: "MasturbateHand",
        label: {
            CN: "掀开裙子",
            EN: "Lift Skirt",
            RU: "Приподнять Юбку",
            UA: "Підняти спідницю",
        },
        dialog: {
            CN: "SourceCharacter掀开TargetCharacter的裙子.",
            EN: "SourceCharacter lifts DestinationCharacter skirt.",
            RU: "SourceCharacter приподнимает юбку TargetCharacter.",
            UA: "SourceCharacter піднімає спідничку TargetCharacter.",
        },
        labelSelf: {
            CN: "掀开裙子",
            EN: "Lift Skirt",
            RU: "Приподнять Юбку",
            UA: "Підняти спідницю",
        },
        dialogSelf: {
            CN: "SourceCharacter掀开PronounPossessive的裙子.",
            EN: "SourceCharacter lifts PronounPossessive's skirt.",
            RU: "SourceCharacter приподнимает свою юбку.",
            UA: "SourceCharacter піднімає свою спідничку.",
        },
    },
    {
        activity: {
            Name: "挥手",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemHands"],
        },
        useImage: "Slap",
        label: {
            CN: "挥手",
            EN: "Wave Hand",
            RU: "Помахать Рукой",
            UA: "Помахати рукою",
        },
        dialog: {
            CN: "SourceCharacter向TargetCharacter挥手.",
            EN: "SourceCharacter waves hand at TargetCharacter.",
            RU: "SourceCharacter машет рукой в сторону TargetCharacter.",
            UA: "SourceCharacter махає рукою в сторону TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "伸出手",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHands"],
        },
        useImage: "Caress",
        labelSelf: {
            CN: "伸出手",
            EN: "Reach Out Hand",
            RU: "Протянуть Руку",
            UA: "Тягнутись рукою",
        },
        dialogSelf: {
            CN: "SourceCharacter伸出自己的手.",
            EN: "SourceCharacter reaches out own hand.",
            RU: "SourceCharacter протягивает руку.",
            UA: "SourceCharacter протягує свою руку.",
        },
    },
    {
        activity: {
            Name: "捂住胸",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemBreast"],
        },
        useImage: "Pull",
        labelSelf: {
            CN: "捂住胸",
            EN: "Cover Chest",
            RU: "Прикрыть Грудь",
            UA: "Прикрити груди",
        },
        dialogSelf: {
            CN: "SourceCharacter捂住自己的胸.",
            EN: "SourceCharacter covers own chest.",
            RU: "SourceCharacter прикрывает свою грудь.",
            UA: "SourceCharacter прикриває свої груди.",
        },
    },
    {
        activity: {
            Name: "手托起下巴",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemMouth"],
        },
        useImage: "Caress",
        label: {
            CN: "手托起下巴",
            EN: "Hand under Chin",
            RU: "Взять за Подбородок",
            UA: "Руку на підборідок",
        },
        dialog: {
            CN: "SourceCharacter用手托起TargetCharacter的下巴.",
            EN: "SourceCharacter places hand under DestinationCharacter chin.",
            RU: "SourceCharacter берет TargetCharacter рукой за подбородок.",
            UA: "SourceCharacter протягує свою руку ставиши на підборідок TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "拽链子",
            Prerequisite: ["UseHands", "UseArms", "TargetHasLeash"],
            MaxProgress: 50,
            Target: ["ItemNeck"],
        },
        useImage: "MasturbateHand",
        label: {
            CN: "拽链子",
            EN: "Pull Chain",
            RU: "Потянуть за Поводок",
            UA: "Тягнути ланцюг",
        },
        dialog: {
            CN: "SourceCharacter拽TargetCharacter的链子.",
            EN: "SourceCharacter pulls DestinationCharacter chain.",
            RU: "SourceCharacter тянет TargetCharacter за поводок.",
            UA: "SourceCharacter тягне TargetCharacter за ланцюг.",
        },
    },
    {
        activity: {
            Name: "弹额头",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemHead"],
        },
        useImage: "Pinch",
        label: {
            CN: "弹额头",
            EN: "Flick Forehead",
            RU: "Поставить Щелбан",
            UA: "Замахнути пальцем в лоб",
        },
        dialog: {
            CN: "SourceCharacter弹了一下TargetCharacter的额头.",
            EN: "SourceCharacter flicks DestinationCharacter forehead.",
            RU: "SourceCharacter ставит щелбан в лоб TargetCharacter.",
            UA: "SourceCharacter замахує пальцем в лоб TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "弹阴蒂",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemVulvaPiercings"],
        },
        useImage: "Pinch",
        label: {
            CN: "弹阴蒂",
            EN: "Flick Clitoris",
            RU: "Щелчек по Клитору",
            UA: "Замахувати пальцем об клітор",
        },
        dialog: {
            CN: "SourceCharacter弹了一下TargetCharacter的阴蒂.",
            EN: "SourceCharacter flicks DestinationCharacter clitoris.",
            RU: "SourceCharacter щелкает TargetCharacter по клитору.",
            UA: "SourceCharacter замахується пальцем об клітор TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "抱腿",
            Prerequisite: ["UseArms"],
            MaxProgress: 50,
            Target: ["ItemLegs"],
        },
        useImage: "Caress",
        label: {
            CN: "抱腿",
            EN: "Hug Legs",
            RU: "Обнять Ноги",
            UA: "Обійняти ноги",
        },
        dialog: {
            CN: "SourceCharacter抱住TargetCharacter的腿.",
            EN: "SourceCharacter hugs DestinationCharacter legs.",
            RU: "SourceCharacter обнимает TargetCharacter за ноги.",
            UA: "SourceCharacter Обіймає ноги TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "拉扯衣角",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemPelvis"],
        },
        useImage: "Pull",
        label: {
            CN: "拉扯衣角",
            EN: "Tug Clothes",
            RU: "Потянуть за Одежду",
            UA: "Тягнути одяг",
        },
        dialog: {
            CN: "SourceCharacter用手拉扯TargetCharacter的衣角.",
            EN: "SourceCharacter tugs at DestinationCharacter clothes.",
            RU: "SourceCharacter тянет TargetCharacter за одежду.",
            UA: "SourceCharacter тягне TargetCharacter за одяг.",
        },
    },
    {
        activity: {
            Name: "拍头",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemHead"],
        },
        useImage: "Slap",
        label: {
            CN: "拍头",
            EN: "Hit The Head",
            RU: "Ударить по Голове",
            UA: "Вдарити по голові",
        },
        dialog: {
            CN: "SourceCharacter拍打TargetCharacter的头.",
            EN: "SourceCharacter hits DestinationCharacter head.",
            RU: "SourceCharacter бьет TargetCharacter по голове.",
            UA: "SourceCharacter б'є по голові TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "竖起尾巴",
            Prerequisite: ["TargetHasCatTail"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemButt"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "竖起尾巴",
            EN: "Raise Tail",
            RU: "Поднять Хвост",
            UA: "Підняти хвіст",
        },
        dialogSelf: {
            CN: "SourceCharacter的尾巴竖了起来.",
            EN: "SourceCharacter raises PronounPossessive tail.",
            RU: "SourceCharacter поднимает свой хвост.",
            UA: "SourceCharacter припіднімає свій хвіст.",
        },
    },
    {
        activity: {
            Name: "炸毛",
            Prerequisite: ["TargetHasCatTail"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemButt"],
        },
        useImage: "Bite",
        labelSelf: {
            CN: "炸毛",
            EN: "Puff Up",
            RU: "Распушиться",
            UA: "Насторожитись",
        },
        dialogSelf: {
            CN: "SourceCharacter弓起后背, 身体的毛发立了起来, 发出嘶的声音.",
            EN: "SourceCharacter arches back, body hair stands up, emitting a hissing sound.",
            RU: "Волосы SourceCharacter встают дыбом пока SourceCharacter шипит, выгибая спину.",
            UA: "SourceCharacter насторожує своє волосся на тілі як лунає гучний звук шипіння.",
        },
    },
    {
        activity: {
            Name: "舔尾巴",
            Prerequisite: ["TargetHasCatTail"],
            MaxProgress: 50,
            Target: ["ItemButt"],
            TargetSelf: true,
        },
        useImage: "MasturbateTongue",
        label: {
            CN: "舔尾巴",
            EN: "Lick Tail",
            RU: "Облизать Хвост",
            UA: "Вилизати хвіст",
        },
        dialog: {
            CN: "SourceCharacter舔TargetCharacter的尾巴.",
            EN: "SourceCharacter licks DestinationCharacter tail.",
            RU: "SourceCharacter облизывает хвост TargetCharacter.",
            UA: "SourceCharacter вилизує хвіст TargetCharacter.",
        },
        labelSelf: {
            CN: "舔尾巴",
            EN: "Lick Tail",
            RU: "Вылизать Хвост",
            UA: "Вилизати хвіст",
        },
        dialogSelf: {
            CN: "SourceCharacter舔自己的尾巴.",
            EN: "SourceCharacter licks own tail.",
            RU: "SourceCharacter вылизывает собственный хвост.",
            UA: "SourceCharacter вилизує свій хвіст.",
        },
    },
    {
        activity: {
            Name: "轻抚尾巴",
            Prerequisite: ["TargetHasTail"],
            MaxProgress: 50,
            Target: ["ItemButt"],
            TargetSelf: true,
        },
        useImage: "Caress",
        label: {
            CN: "轻抚尾巴",
            EN: "Gently Stroke Tail",
            RU: "Нежно Погладить Хвостик",
            UA: "Ніжно погладити хвіст",
        },
        dialog: {
            CN: "SourceCharacter轻抚TargetCharacter的尾巴.",
            EN: "SourceCharacter gently strokes DestinationCharacter tail.",
            RU: "SourceCharacter нежно гладит TargetCharacter за хвостик.",
            UA: "SourceCharacter ніжно гладить хвіст TargetCharacter.",
        },
        labelSelf: {
            CN: "轻抚尾巴",
            EN: "Gently Stroke Tail",
            RU: "Нежно Подрочить Хвостик",
            UA: "Ніжно погладити хвіст",
        },
        dialogSelf: {
            CN: "SourceCharacter轻抚PronounPossessive的尾巴.",
            EN: "SourceCharacter gently strokes PronounPossessive's tail.",
            RU: "SourceCharacter нежно дрочит свой хвостик.",
            UA: "SourceCharacter ніжно погдаджує свій свіст.",
        },
    },
    {
        activity: {
            Name: "尾巴叼在嘴里",
            Prerequisite: ["TargetHasCatTail"],
            MaxProgress: 50,
            Target: ["ItemButt"],
            TargetSelf: true,
        },
        useImage: "Kiss",
        label: {
            CN: "尾巴叼在嘴里",
            EN: "Hold Tail in Mouth",
            RU: "Взять Хвост в Рот",
            UA: "Тримати хвіст в роті",
        },
        dialog: {
            CN: "SourceCharacter叼起TargetCharacter的尾巴.",
            EN: "SourceCharacter holds DestinationCharacter tail in mouth.",
            RU: "SourceCharacter сует хвост TargetCharacter себе в рот.",
            UA: "SourceCharacter всовує хвіст TargetCharacter собі в рот і тримає ніжно.",
        },
        labelSelf: {
            CN: "尾巴叼在嘴里",
            EN: "Hold Tail in Mouth",
            RU: "Взять Хвост в Рот",
            UA: "Тримати хвіст в роті",
        },
        dialogSelf: {
            CN: "SourceCharacter叼起自己的尾巴.",
            EN: "SourceCharacter holds own tail in mouth.",
            RU: "SourceCharacter сует собственный хвост себе в рот.",
            UA: "SourceCharacter всовує і тримає свій хвіст в роті.",
        },
    },
    {
        activity: {
            Name: "抬起屁股",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemButt"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "抬起屁股",
            EN: "Lift Buttocks",
            RU: "Поднять Булочки",
            UA: "Підняти сідниці",
        },
        dialogSelf: {
            CN: "SourceCharacter弯腰抬起PronounPossessive的屁股.",
            EN: "SourceCharacter bends over, lifting PronounPossessive buttocks.",
            RU: "SourceCharacter наклоняется, приподнимая свои ягодицы.",
            UA: "SourceCharacter нахиляється, піднімаючи і показуючи свої сідниці.",
        },
    },
    {
        activity: {
            Name: "扇动翅膀",
            Prerequisite: ["TargetHasWings"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemArms"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "扇动翅膀",
            EN: "Flap Wings",
            RU: "Взмахнуть Крыльями",
            UA: "Розмахувати крилами",
        },
        dialogSelf: {
            CN: "SourceCharacter扇动PronounPossessive的翅膀.",
            EN: "SourceCharacter flaps PronounPossessive wings.",
            RU: "SourceCharacter взмахивает своими крыльями.",
            UA: "SourceCharacter розмахує свої крила.",
        },
    },
    {
        activity: {
            Name: "下巴搭在肩膀上",
            Prerequisite: [],
            MaxProgress: 50,
            Target: ["ItemNeck"],
        },
        useImage: "RestHead",
        label: {
            CN: "下巴搭在肩膀上",
            EN: "Chin on Shoulder",
            RU: "Подбородок на Плечо.",
            UA: "Підборідок на плечі",
        },
        dialog: {
            CN: "SourceCharacter把下巴搭在TargetCharacter的肩膀上.",
            EN: "SourceCharacter places chin on DestinationCharacter shoulder.",
            RU: "SourceCharacter ложит подбородок на плечо TargetCharacter.",
            UA: "SourceCharacter ставить свій підборідок на плече TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "手臂搭在肩膀上",
            Prerequisite: ["UseArms"],
            MaxProgress: 50,
            Target: ["ItemNeck"],
        },
        useImage: "Slap",
        label: {
            CN: "手臂搭在肩膀上",
            EN: "Arm on Shoulder",
            RU: "Руку на Плечо",
            UA: "Рука на плече",
        },
        dialog: {
            CN: "SourceCharacter把手臂搭在TargetCharacter的肩膀上.",
            EN: "SourceCharacter places arm on DestinationCharacter shoulder.",
            RU: "SourceCharacter кладет свою руку на плечо TargetCharacter.",
            UA: "SourceCharacter ставить свою руку на плече TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "搂腰",
            Prerequisite: ["UseArms", "UseHands"],
            MaxProgress: 50,
            Target: ["ItemTorso"],
        },
        useImage: "SistersHug",
        label: {
            CN: "搂腰",
            EN: "Embrace Waist",
            RU: "Приобнять за Талию",
            UA: "Обійняти за талію",
        },
        dialog: {
            CN: "SourceCharacter搂住TargetCharacter的腰.",
            EN: "SourceCharacter embraces DestinationCharacter waist.",
            RU: "SourceCharacter приобнимает TargetCharacter за талию.",
            UA: "SourceCharacter обіймає TargetCharacter за талію тягнучи їх ближче до SourceCharacter.",
        },
    },
    {
        activity: {
            Name: "叉腰",
            Prerequisite: ["UseArms", "UseHands"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemTorso"],
        },
        useImage: "Choke",
        labelSelf: {
            CN: "叉腰",
            EN: "Put Hands on Hips",
            RU: "Руки на Бедра",
            UA: "Руки на стегна",
        },
        dialogSelf: {
            CN: "SourceCharacter双手叉在腰上.",
            EN: "SourceCharacter puts PronounPossessive hands on PronounPossessive hips.",
            RU: "SourceCharacter кладет руки на бедра.",
            UA: "SourceCharacter ставить свої руки на свої стегна.",
        },
    },
    {
        activity: {
            Name: "身体颤抖",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemTorso"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "身体颤抖",
            EN: "Body Trembles",
            RU: "Дрожать",
            UA: "Тремтіти тілом",
        },
        dialogSelf: {
            CN: "SourceCharacter颤抖着身体.",
            EN: "SourceCharacter's body trembles.",
            RU: "SourceCharacter дрожит всем телом.",
            UA: "Тіло SourceCharacter тремтить як мурашки проходять по PronounPossessive спинію",
        },
    },
    {
        activity: {
            Name: "身体抽搐",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemTorso"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "身体抽搐",
            EN: "Body Twitches",
            RU: "Подрагивать Телом",
            UA: "Тремор тіла",
        },
        dialogSelf: {
            CN: "SourceCharacter身体抽搐着.",
            EN: "SourceCharacter's body twitches.",
            RU: "SourceCharacter подрагивает всем телом.",
            UA: "Тіло SourceCharacter тремтить.",
        },
    },
    {
        activity: {
            Name: "托起乳房",
            Prerequisite: [],
            MaxProgress: 50,
            Target: ["ItemBreast"],
            TargetSelf: true,
        },
        useImage: "Wiggle",
        label: {
            CN: "托起乳房",
            EN: "Lift Breasts",
            RU: "Приподнять Грудь",
            UA: "Підняти груди",
        },
        dialog: {
            CN: "SourceCharacter托起TargetCharacter的双乳.",
            EN: "SourceCharacter lifts DestinationCharacter breasts.",
            RU: "SourceCharacter приподнимает грудь TargetCharacter.",
            UA: "SourceCharacter ніжно піднямає груди TargetCharacter.",
        },
        labelSelf: {
            CN: "托起乳房",
            EN: "Lift Breasts",
            RU: "Приподнять Грудь",
            UA: "Підняти груди",
        },
        dialogSelf: {
            CN: "SourceCharacter托起PronounPossessive的双乳.",
            EN: "SourceCharacter lifts PronounPossessive's breasts.",
            RU: "SourceCharacter приподнимает свою грудь.",
            UA: "SourceCharacter піднімає свої ж груди.",
        },
    },
    {
        activity: {
            Name: "揉搓乳头",
            Prerequisite: ["UseHands", "UseArms", "ZoneNaked"],
            MaxProgress: 90,
            Target: ["ItemNipples"],
            TargetSelf: true,
        },
        useImage: "Pinch",
        label: {
            CN: "揉搓乳头",
            EN: "Rub Nipples",
            RU: "Поиграть с Сосками",
            UA: "Терти соски",
        },
        dialog: {
            CN: "SourceCharacter揉搓TargetCharacter的乳头.",
            EN: "SourceCharacter uses hands to pinch DestinationCharacter nipples, rubbing them.",
            RU: "SourceCharacter вытягивает соски TargetCharacter и массирует их.",
            UA: "SourceCharacter ніжно щипає соски TargetCharacter підтягуючи їх перед тим, як терти їх пальцями.",
        },
        labelSelf: {
            CN: "揉搓乳头",
            EN: "Rub Nipples",
            RU: "Поиграть с Сосками",
            UA: "Терти соски",
        },
        dialogSelf: {
            CN: "SourceCharacter揉搓PronounPossessive的乳头.",
            EN: "SourceCharacter uses hands to pinch PronounPossessive's nipples, rubbing them.",
            RU: "SourceCharacter оттягивает свои соски и массирует их.",
            UA: "SourceCharacter ніжно щипає свої соски, підтягуючи їх перед тим, як терти їх пальцями.",
        },
    },
    {
        activity: {
            Name: "双腿颤抖",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemLegs"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "双腿颤抖",
            EN: "Shaking legs",
            RU: "Ноги Дрожат",
            UA: "Трясти ногами",
        },
        dialogSelf: {
            CN: "SourceCharacter颤抖着双腿.",
            EN: "SourceCharacter's legs tremble.",
            RU: "Ноги SourceCharacter трясутся от страха.",
            UA: "Ноги SourceCharacter трусяться.",
        },
    },
    {
        activity: {
            Name: "摇晃双腿",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemLegs"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "摇晃双腿",
            EN: "Shake Legs",
            RU: "Трясти Ногами",
            UA: "Трясти ногами",
        },
        dialogSelf: {
            CN: "SourceCharacter摇晃PronounPossessive的双腿.",
            EN: "SourceCharacter shakes own legs.",
            RU: "SourceCharacter трясет своими ногами.",
            UA: "SourceCharacter трусить своїми ногами.",
        },
    },
    {
        activity: {
            Name: "流出液体",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemVulva"],
        },
        useImage: "MoanGagWhimper",
        labelSelf: {
            CN: "流出液体",
            EN: "Liquid Flows",
            RU: "Потечь",
            UA: "Підтікати",
        },
        dialogSelf: {
            CN: "SourceCharacter股间有液体顺着的大腿流下.",
            EN: "Liquid flows down SourceCharacter's thighs.",
            RU: "Жидкость стекает по ляжкам SourceCharacter.",
            UA: "SourceCharacter стікає своєю рідиною по своїх стегнах.",
        },
    },
    {
        activity: {
            Name: "失禁",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemVulva"],
        },
        useImage: "MoanGagWhimper",
        labelSelf: {
            CN: "失禁",
            EN: "Incontinence",
            RU: "Недержание",
            UA: "Недержання",
        },
        dialogSelf: {
            CN: "SourceCharacter的尿液顺着PronounPossessive大腿流下.",
            EN: "SourceCharacter's urine flows down PronounPossessive thighs.",
            RU: "SourceCharacter не выдерживает и писается, обтекая мочой на ногах.",
            UA: "Сеча тече по стегнам SourceCharacter.",
        },
    },
    {
        activity: {
            Name: "跺脚",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemBoots"],
        },
        useImage: "Step",
        labelSelf: {
            CN: "跺脚",
            EN: "Stamp Feet",
            RU: "Топать",
            UA: "Тупотіти ногами",
        },
        dialogSelf: {
            CN: "SourceCharacter不停地跺脚.",
            EN: "SourceCharacter keeps stamping PronounPossessive feet.",
            RU: "SourceCharacter недовольно топает ногами.",
            UA: "SourceCharacter тупотить своїми ногами.",
        },
    },
    {
        activity: {
            Name: "撩头发",
            Prerequisite: ["UseArms", "UseHands"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHood"],
        },
        useImage: "Caress",
        labelSelf: {
            CN: "撩头发",
            EN: "Toss Hair",
            RU: "Поправить Волосы",
            UA: "Підкинути волосся",
        },
        dialogSelf: {
            CN: "SourceCharacter撩起头发挂在耳边.",
            EN: "SourceCharacter tosses PronounPossessive hair, letting it hang behind PronounPossessive ears.",
            RU: "SourceCharacter поправляет волосы, заводя их за ухо.",
            UA: "SourceCharacter Підкридує своє волосся за PronounPossessive вухами.",
        },
    },
    {
        activity: {
            Name: "手指插进阴道",
            Prerequisite: ["UseHands", "ZoneNaked", "TargetZoneNaked"],
            MaxProgress: 90,
            Target: ["ItemVulva"],
            TargetSelf: true,
        },
        useImage: "MasturbateHand",
        label: {
            CN: "手指插进阴道",
            EN: "Insert Finger into Vagina",
            RU: "Вставить Палец в Вагину",
            UA: "Вставити палець у вагіну",
        },
        dialog: {
            CN: "SourceCharacter手指插进TargetCharacter的阴道内.",
            EN: "SourceCharacter inserts finger into DestinationCharacter vagina.",
            RU: "SourceCharacter вставляет палец в вагину TargetCharacter.",
            UA: "SourceCharacter вставляє палець у вагіну TargetCharacter.",
        },
        labelSelf: {
            CN: "手指插进阴道",
            EN: "Insert Finger into Vagina",
            RU: "Вставить Палец в Вагину",
            UA: "Вставити палець у вагіну",
        },
        dialogSelf: {
            CN: "SourceCharacter手指插进自己的的阴道内.",
            EN: "SourceCharacter inserts finger into own vagina.",
            RU: "SourceCharacter вставляет палец в свою вагину.",
            UA: "SourceCharacter вставляє собі в вагіну палець.",
        },
    },
    {
        activity: {
            Name: "拔出自己的手指",
            Prerequisite: ["UseHands", "ZoneNaked", "TargetZoneNaked"],
            MaxProgress: 90,
            Target: ["ItemVulva"],
            TargetSelf: true,
        },
        useImage: "MasturbateHand",
        label: {
            CN: "拔出自己的手指",
            EN: "Remove Finger",
            RU: "Вытащить Палец",
            UA: "Витягнути палець",
        },
        dialog: {
            CN: "SourceCharacter从TargetCharacter的阴道内拔出自己的手指,手指连着PronounPossessive的爱液.",
            EN: "SourceCharacter removes own finger from DestinationCharacter vagina, the finger coated with PronounPossessive love fluids.",
            RU: "SourceCharacter вынимает покрытый любовным соком палец из вагины TargetCharacter.",
            UA: "SourceCharacter витягує палець покритий тонким шаром сексапільного соку з вагіни TargetCharacter.",
        },
        labelSelf: {
            CN: "拔出自己的手指",
            EN: "Remove Finger",
            RU: "Вытащить Палец",
            UA: "Витягнути палець",
        },
        dialogSelf: {
            CN: "SourceCharacter从PronounPossessive的阴道内拔出自己的手指,手指连着自己的爱液.",
            EN: "SourceCharacter removes own finger from PronounPossessive's vagina, the finger coated with SourceCharacter's love fluids.",
            RU: "SourceCharacter вынимает покрытый любовным соком палец из своей вагины.",
            UA: "SourceCharacter витягує палець зі своєї вагіни як воно покрите тонким шаром PronounPossessive ж вагінальним соком.",
        },
    },
    {
        activity: {
            Name: "蠕动手指",
            Prerequisite: ["UseHands", "ZoneNaked", "TargetZoneNaked"],
            MaxProgress: 100,
            Target: ["ItemVulva"],
            TargetSelf: true,
        },
        useImage: "Grope",
        label: {
            CN: "蠕动手指",
            EN: "Wriggle Finger",
            RU: "Двигать Пальцем",
            UA: "SourceCharacter TargetCharacter.",
        },
        dialog: {
            CN: "SourceCharacter在TargetCharacter的阴道内蠕动手指.",
            EN: "SourceCharacter wriggles a finger inside DestinationCharacter vagina.",
            RU: "SourceCharacter двигает пальцем внутри вагины TargetCharacter.",
            UA: "SourceCharacter TargetCharacter.",
        },
        labelSelf: {
            CN: "蠕动手指",
            EN: "Wriggle Finger",
            RU: "Двигать Пальцем",
            UA: "Рухати пальцями",
        },
        dialogSelf: {
            CN: "SourceCharacter在PronounPossessive的阴道内蠕动手指.",
            EN: "SourceCharacter wriggles a finger inside PronounPossessive's vagina.",
            RU: "SourceCharacter двигает пальцем внутри своей вагины.",
            UA: "SourceCharacter дражнить себе рухаючи своїми пальцями в середині своєї вагіни паддрочуючи.",
        },
    },
    {
        activity: {
            Name: "快速抽插",
            Prerequisite: ["UseHands", "ZoneNaked", "TargetZoneNaked"],
            MaxProgress: 100,
            Target: ["ItemVulva"],
            TargetSelf: true,
        },
        useImage: "Pinch",
        label: {
            CN: "快速抽插",
            EN: "Quickly Thrust",
            RU: "Интим",
            UA: "Вштовхувати",
        },
        dialog: {
            CN: "SourceCharacter的手在TargetCharacter的阴道内快速抽插.",
            EN: "SourceCharacter's hand quickly thrusts in and out of DestinationCharacter vagina, rubbing and kneading.",
            RU: "Рука SourceCharacter быстро входит и выходит из вагины TargetCharacter, растягивая и разминая её.",
            UA: "SourceCharacter швидко вштовхує своїми пальцями в вагіну TargetCharacter дразливо бавлячись з PronounPossessive ж вагіною.",
        },
        labelSelf: {
            CN: "快速抽插",
            EN: "Quickly Thrust",
            RU: "Интим",
            UA: "Вштовхувати",
        },
        dialogSelf: {
            CN: "SourceCharacter的手在PronounPossessive的阴道内快速抽插.",
            EN: "SourceCharacter's hand quickly thrusts in and out of PronounPossessive's vagina, rubbing and kneading.",
            RU: "SourceCharacter быстро орудует рукой, входя и выхоля из своей вагины он растягивает и разминает её.",
            UA: "SourceCharacter швидко вштовхує своїми палцями в себе дразливо бавлячись з PronounPossessive ж вагіною.",
        },
    },
    {
        activity: {
            Name: "钩住阴蒂环",
            Prerequisite: ["UseHands", "TargetHasItemVulvaPiercings"],
            MaxProgress: 50,
            Target: ["ItemVulvaPiercings"],
            TargetSelf: true,
        },
        useImage: "Pinch",
        label: {
            CN: "钩住阴蒂环",
            EN: "Hook Clitoral Piercing",
            RU: "Подцепить за Пирсинг",
            UA: "Тягнути кліторальний пірсінг",
        },
        dialog: {
            CN: "SourceCharacter钩住TargetCharacter的阴蒂环.",
            EN: "SourceCharacter hooks onto DestinationCharacter clitoral piercing.",
            RU: "SourceCharacter цепляется за пирсинг на клиторе TargetCharacter.",
            UA: "SourceCharacter підтягує кліторальний пірсінг TargetCharacter дразнячи PronounPossessive.",
        },
        labelSelf: {
            CN: "钩住阴蒂环",
            EN: "Hook Clitoral Piercing",
            RU: "Подцепить за Пирсинг",
            UA: "Тягнути кліторальний пірсінг",
        },
        dialogSelf: {
            CN: "SourceCharacter钩住自己的阴蒂环.",
            EN: "SourceCharacter hooks onto own clitoral piercing.",
            RU: "SourceCharacter цепляется за пирсинг на своем клиторе.",
            UA: "SourceCharacter підтягує свій кліторальний пірсінг ніжно дразнячи себе.",
        },
    },
    {
        activity: {
            Name: "拉扯阴蒂环",
            Prerequisite: ["UseHands", "TargetHasItemVulvaPiercings"],
            MaxProgress: 50,
            Target: ["ItemVulvaPiercings"],
            TargetSelf: true,
        },
        useImage: "Pinch",
        label: {
            CN: "拉扯阴蒂环",
            EN: "Tug Clitoral Piercing",
            RU: "Потянуть за Пирсинг",
            UA: "Тягнути кліторальний пірсінг",
        },
        dialog: {
            CN: "SourceCharacter拉了一下TargetCharacter的阴蒂环.",
            EN: "SourceCharacter tugs on DestinationCharacter clitoral piercing and then releases it.",
            RU: "SourceCharacter тянет за пирсинг на клиторе TargetCharacter.",
            UA: "SourceCharacter підтягує кліторальний пірсінг TargetCharacter дразнячи PronounPossessive.",
        },
        labelSelf: {
            CN: "拉扯阴蒂环",
            EN: "Tug Clitoral Piercing",
            RU: "Потянуть за Пирсинг",
            UA: "Тягнути кліторальний пірсінг",
        },
        dialogSelf: {
            CN: "SourceCharacter拉了一下自己的阴蒂环.",
            EN: "SourceCharacter tugs on own clitoral piercing and then releases it.",
            RU: "SourceCharacter тянет за пирсинг на своем клиторе.",
            UA: "SourceCharacter підтягує свій кліторальний пірсінг ніжно дразнячи себе.",
        },
    },
];

export default function () {
    ActivityManager.addCustomActivities(activities);
}
