import { ActivityManager } from "../activityForward";

/** @type { CustomActivity []} */
const activities = [
    {
        activity: {
            Name: "捏脸",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemMouth"],
            TargetSelf: true,
        },
        useImage: "Pinch",
        label: {
            CN: "捏脸",
            EN: "Pinch Face",
            RU: "Ущипнуть за Лицо",
            UA: "Вщипнути обличчя",
        },
        dialog: {
            CN: "SourceCharacter捏了捏TargetCharacter的脸.",
            EN: "SourceCharacter pinches DestinationCharacter face.",
            RU: "SourceCharacter щипает TargetCharacter за лицо.",
            UA: "SourceCharacter вщипує обличчя TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "戳手臂",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemArms"],
            TargetSelf: true,
        },
        useImage: "Caress",
        label: {
            CN: "戳手臂",
            EN: "Poke Arm",
            RU: "Тыкнуть в Руку",
            UA: "Тицяти руку",
        },
        dialog: {
            CN: "SourceCharacter戳了戳TargetCharacter的手臂.",
            EN: "SourceCharacter pokes DestinationCharacter arm.",
            RU: "SourceCharacter тыкает TargetCharacter в руку.",
            UA: "SourceCharacter тицяє руку TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "揉脸",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemMouth"],
            TargetSelf: true,
        },
        useImage: "Wiggle",
        label: {
            CN: "揉脸",
            EN: "Rub Face",
            RU: "Потереть Лицо",
            UA: "Потерти обличчя",
        },
        dialog: {
            CN: "SourceCharacter揉了揉TargetCharacter的脸.",
            EN: "SourceCharacter rubs DestinationCharacter face.",
            RU: "SourceCharacter трет лицо TargetCharacter.",
            UA: "SourceCharacter тре обличчя TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "摇晃手臂",
            Prerequisite: ["UseHands"],
            MaxProgress: 50,
            Target: ["ItemArms"],
            TargetSelf: true,
        },
        useImage: "Wiggle",
        label: {
            CN: "摇晃手臂",
            EN: "Shake Arms",
            RU: "Трясти за Плечи",
            UA: "Трусити руки",
        },
        dialog: {
            CN: "SourceCharacter摇晃TargetCharacter的手臂.",
            EN: "SourceCharacter shakes DestinationCharacter arms.",
            RU: "SourceCharacter трясет TargetCharacter за плечи .",
            UA: "SourceCharacter трусить руки TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "轻推",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemTorso"],
        },
        useImage: "Slap",
        label: {
            CN: "轻推",
            EN: "Light Push",
            RU: "Легонько Толкнуть",
            UA: "Ніжно штовхнути",
        },
        dialog: {
            CN: "SourceCharacter用手轻推TargetCharacter的身体.",
            EN: "SourceCharacter lightly pushes DestinationCharacter body.",
            RU: "SourceCharacter легонько толкает TargetCharacter",
            UA: "SourceCharacter легенько штовхає TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "扭动手腕",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHands"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "扭动手腕",
            EN: "Twist Wrists",
            RU: "Вращать Кистями",
            UA: "Скрутити зап'ястя",
        },
        dialogSelf: {
            CN: "SourceCharacter扭动PronounPossessive的手腕.",
            EN: "SourceCharacter twists PronounPossessive wrists.",
            RU: "SourceCharacter вращает кистями.",
            UA: "SourceCharacter скручує собі зап'ястя.",
        },
    },
    {
        activity: {
            Name: "挠头",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHead"],
        },
        useImage: "Pull",
        labelSelf: {
            CN: "挠头",
            EN: "Scratch Head",
            RU: "Почесать Голову",
            UA: "Почухати голову.",
        },
        dialogSelf: {
            CN: "SourceCharacter挠了挠PronounPossessive的头.",
            EN: "SourceCharacter scratches PronounPossessive own head",
            RU: "SourceCharacter чешет голову.",
            UA: "SourceCharacter чухає свою голову.",
        },
    },
    {
        activity: {
            Name: "盖住耳朵",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemEars"],
            TargetSelf: true,
        },
        useImage: "HandGag",
        label: {
            CN: "盖住耳朵",
            EN: "Cover Ears",
            RU: "Закрыть Уши",
            UA: "Закрити вуха",
        },
        dialog: {
            CN: "SourceCharacter用手盖住了TargetCharacter的耳朵.",
            EN: "SourceCharacter covers DestinationCharacter ears with hands.",
            RU: "SourceCharacter прикрывает уши TargetCharacter руками.",
            UA: "SourceCharacter закриває вуха TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "遮住眼睛",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemHead"],
            TargetSelf: true,
        },
        useImage: "HandGag",
        label: {
            CN: "遮住眼睛",
            EN: "Cover Eyes",
            RU: "Прикрыть Глазки",
            UA: "Прикрити очі",
        },
        dialog: {
            CN: "SourceCharacter用手遮住了TargetCharacter的眼睛.",
            EN: "SourceCharacter covers DestinationCharacter eyes with hands.",
            RU: "SourceCharacter прикрывает глазки TargetCharacter своими руками.",
            UA: "SourceCharacter закриває очі TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "掀开裙子",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemButt"],
            TargetSelf: true,
        },
        useImage: "MasturbateHand",
        label: {
            CN: "掀开裙子",
            EN: "Lift Skirt",
            RU: "Приподнять Юбку",
            UA: "Підняти спідницю",
        },
        dialog: {
            CN: "SourceCharacter掀开TargetCharacter的裙子.",
            EN: "SourceCharacter lifts DestinationCharacter skirt.",
            RU: "SourceCharacter приподнимает юбку TargetCharacter.",
            UA: "SourceCharacter піднімає спідничку TargetCharacter.",
        },
    },
    {
        activity: {
            Name: "拽链子",
            Prerequisite: ["UseHands", "UseArms", "TargetHasLeash"],
            MaxProgress: 50,
            Target: ["ItemNeck"],
        },
        useImage: "MasturbateHand",
        label: {
            CN: "拽链子",
            EN: "Pull Chain",
            RU: "Потянуть за Поводок",
            UA: "Тягнути ланцюг",
        },
        dialog: {
            CN: "SourceCharacter拽TargetCharacter的链子.",
            EN: "SourceCharacter pulls DestinationCharacter chain.",
            RU: "SourceCharacter тянет TargetCharacter за поводок.",
            UA: "SourceCharacter тягне TargetCharacter за ланцюг.",
        },
    },
    {
        activity: {
            Name: "拉扯衣角",
            Prerequisite: ["UseHands", "UseArms"],
            MaxProgress: 50,
            Target: ["ItemPelvis"],
        },
        useImage: "Pull",
        label: {
            CN: "拉扯衣角",
            EN: "Tug Clothes",
            RU: "Потянуть за Одежду",
            UA: "Тягнути одяг",
        },
        dialog: {
            CN: "SourceCharacter用手拉扯TargetCharacter的衣角.",
            EN: "SourceCharacter tugs at DestinationCharacter clothes.",
            RU: "SourceCharacter тянет TargetCharacter за одежду.",
            UA: "SourceCharacter тягне TargetCharacter за одяг.",
        },
    },
    {
        activity: {
            Name: "抬起屁股",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemButt"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "抬起屁股",
            EN: "Lift Buttocks",
            RU: "Поднять Булочки",
            UA: "Підняти сідниці",
        },
        dialogSelf: {
            CN: "SourceCharacter弯腰抬起PronounPossessive的屁股.",
            EN: "SourceCharacter bends over, lifting PronounPossessive buttocks.",
            RU: "SourceCharacter наклоняется, приподнимая свои ягодицы.",
            UA: "SourceCharacter нахиляється, піднімаючи і показуючи свої сідниці.",
        },
    },
    {
        activity: {
            Name: "搂腰",
            Prerequisite: ["UseArms", "UseHands"],
            MaxProgress: 50,
            Target: ["ItemTorso"],
        },
        useImage: "SistersHug",
        label: {
            CN: "搂腰",
            EN: "Embrace Waist",
            RU: "Приобнять за Талию",
            UA: "Обійняти за талію",
        },
        dialog: {
            CN: "SourceCharacter搂住TargetCharacter的腰.",
            EN: "SourceCharacter embraces DestinationCharacter waist.",
            RU: "SourceCharacter приобнимает TargetCharacter за талию.",
            UA: "SourceCharacter обіймає TargetCharacter за талію тягнучи їх ближче до SourceCharacter.",
        },
    },
    {
        activity: {
            Name: "叉腰",
            Prerequisite: ["UseArms", "UseHands"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemTorso"],
        },
        useImage: "Choke",
        labelSelf: {
            CN: "叉腰",
            EN: "Put Hands on Hips",
            RU: "Руки на Бедра",
            UA: "Руки на стегна",
        },
        dialogSelf: {
            CN: "SourceCharacter双手叉在腰上.",
            EN: "SourceCharacter puts PronounPossessive hands on PronounPossessive hips.",
            RU: "SourceCharacter кладет руки на бедра.",
            UA: "SourceCharacter ставить свої руки на свої стегна.",
        },
    },
    {
        activity: {
            Name: "身体颤抖",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemTorso"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "身体颤抖",
            EN: "Body Trembles",
            RU: "Дрожать",
            UA: "Тремтіти тілом",
        },
        dialogSelf: {
            CN: "SourceCharacter颤抖着身体.",
            EN: "SourceCharacter's body trembles.",
            RU: "SourceCharacter дрожит всем телом.",
            UA: "Тіло SourceCharacter тремтить як мурашки проходять по PronounPossessive спинію",
        },
    },
    {
        activity: {
            Name: "身体抽搐",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemTorso"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "身体抽搐",
            EN: "Body Twitches",
            RU: "Подрагивать Телом",
            UA: "Тремор тіла",
        },
        dialogSelf: {
            CN: "SourceCharacter身体抽搐着.",
            EN: "SourceCharacter's body twitches.",
            RU: "SourceCharacter подрагивает всем телом.",
            UA: "Тіло SourceCharacter тремтить.",
        },
    },
    {
        activity: {
            Name: "双腿颤抖",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemLegs"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "双腿颤抖",
            EN: "Shaking legs",
            RU: "Ноги Дрожат",
            UA: "Трясти ногами",
        },
        dialogSelf: {
            CN: "SourceCharacter颤抖着双腿.",
            EN: "SourceCharacter's legs tremble.",
            RU: "Ноги SourceCharacter трясутся от страха.",
            UA: "Ноги SourceCharacter трусяться.",
        },
    },
    {
        activity: {
            Name: "摇晃双腿",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemLegs"],
        },
        useImage: "Wiggle",
        labelSelf: {
            CN: "摇晃双腿",
            EN: "Shake Legs",
            RU: "Трясти Ногами",
            UA: "Трясти ногами",
        },
        dialogSelf: {
            CN: "SourceCharacter摇晃PronounPossessive的双腿.",
            EN: "SourceCharacter shakes own legs.",
            RU: "SourceCharacter трясет своими ногами.",
            UA: "SourceCharacter трусить своїми ногами.",
        },
    },
    {
        activity: {
            Name: "流出液体",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemVulva"],
        },
        useImage: "MoanGagWhimper",
        labelSelf: {
            CN: "流出液体",
            EN: "Liquid Flows",
            RU: "Потечь",
            UA: "Підтікати",
        },
        dialogSelf: {
            CN: "SourceCharacter股间有液体顺着的大腿流下.",
            EN: "Liquid flows down SourceCharacter's thighs.",
            RU: "Жидкость стекает по ляжкам SourceCharacter.",
            UA: "SourceCharacter стікає своєю рідиною по своїх стегнах.",
        },
    },
    {
        activity: {
            Name: "失禁",
            Prerequisite: ["TargetHasItemVulva"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemVulva"],
        },
        useImage: "MoanGagWhimper",
        labelSelf: {
            CN: "失禁",
            EN: "Incontinence",
            RU: "Недержание",
            UA: "Недержання",
        },
        dialogSelf: {
            CN: "SourceCharacter的尿液顺着PronounPossessive大腿流下.",
            EN: "SourceCharacter's urine flows down PronounPossessive thighs.",
            RU: "SourceCharacter не выдерживает и писается, обтекая мочой на ногах.",
            UA: "Сеча тече по стегнам SourceCharacter.",
        },
    },
    {
        activity: {
            Name: "跺脚",
            Prerequisite: [],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemBoots"],
        },
        useImage: "Step",
        labelSelf: {
            CN: "跺脚",
            EN: "Stamp Feet",
            RU: "Топать",
            UA: "Тупотіти ногами",
        },
        dialogSelf: {
            CN: "SourceCharacter不停地跺脚.",
            EN: "SourceCharacter keeps stamping PronounPossessive feet.",
            RU: "SourceCharacter недовольно топает ногами.",
            UA: "SourceCharacter тупотить своїми ногами.",
        },
    },
    {
        activity: {
            Name: "撩头发",
            Prerequisite: ["UseArms", "UseHands"],
            MaxProgress: 50,
            Target: [],
            TargetSelf: ["ItemHood"],
        },
        useImage: "Caress",
        labelSelf: {
            CN: "撩头发",
            EN: "Toss Hair",
            RU: "Поправить Волосы",
            UA: "Підкинути волосся",
        },
        dialogSelf: {
            CN: "SourceCharacter撩起头发挂在耳边.",
            EN: "SourceCharacter tosses PronounPossessive hair, letting it hang behind PronounPossessive ears.",
            RU: "SourceCharacter поправляет волосы, заводя их за ухо.",
            UA: "SourceCharacter Підкридує своє волосся за PronounPossessive вухами.",
        },
    },
];

export default function () {
    ActivityManager.addCustomActivities(activities);
}
